export interface SalesApprovalDetails {
    id:  string,
    product_title: string,
    description:string,
    model:string,
    brand:string,
    product_code: number,
    part_no:number,
    pack_size: number,
    hsn_code:number,
    gst:number,
    quantity: number,
    uom: number,
    unit_price:number,
}
